# -*- coding: utf-8 -*-
"""EstatísticasBrasileirao - Estudo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1gIlWZeGdZlJJM_SmktUe7gwPYFM04W
"""

import pandas as pd
from google.colab import drive
from tabulate import tabulate

df = pd.read_excel('/content/drive/My Drive/Arquivos_CSV/BRA.xlsx')

columns = ['Season', 'Home', 'Away', 'Res']
df_selected = df[columns]

df_2023 = df_selected[df_selected['Season'] == 2023]

if not df_2023.empty:
    estatisticas_2023 = {}

    for index, row in df_2023.iterrows():
        home_team = row['Home']
        away_team = row['Away']
        resultado = row['Res']

        if home_team not in estatisticas_2023:
            estatisticas_2023[home_team] = {'Vitórias': 0, 'Derrotas': 0, 'Empates': 0}

        if away_team not in estatisticas_2023:
            estatisticas_2023[away_team] = {'Vitórias': 0, 'Derrotas': 0, 'Empates': 0}

        if resultado == 'H':
            estatisticas_2023[home_team]['Vitórias'] += 1
            estatisticas_2023[away_team]['Derrotas'] += 1
        elif resultado == 'A':
            estatisticas_2023[home_team]['Derrotas'] += 1
            estatisticas_2023[away_team]['Vitórias'] += 1
        else:
            estatisticas_2023[home_team]['Empates'] += 1
            estatisticas_2023[away_team]['Empates'] += 1

    df_estatisticas_2023 = pd.DataFrame.from_dict(estatisticas_2023, orient='index')

    df_estatisticas_2023 = df_estatisticas_2023.sort_values(by='Vitórias', ascending=False)

    df_estatisticas_2023['Ranking'] = range(1, len(df_estatisticas_2023) + 1)

    df_estatisticas_2023 = df_estatisticas_2023.reset_index().rename(columns={'index': 'Time'})

    df_estatisticas_2023 = df_estatisticas_2023[['Ranking', 'Time', 'Vitórias', 'Empates', 'Derrotas']]

    print(tabulate(df_estatisticas_2023, headers='keys', tablefmt='pipe', showindex=False, stralign='center', numalign='center'))

import pandas as pd
from google.colab import drive
from tabulate import tabulate


df = pd.read_excel('/content/drive/My Drive/Arquivos_CSV/BRA.xlsx')

columns = ['Season', 'Home', 'Away', 'Res']
df_selected = df[columns]

df_2023 = df_selected[df_selected['Season'] == 2023]

if not df_2023.empty:
    estatisticas_2023 = {}

    for index, row in df_2023.iterrows():
        home_team = row['Home']
        away_team = row['Away']
        resultado = row['Res']

        if home_team not in estatisticas_2023:
            estatisticas_2023[home_team] = {'Vitórias': 0, 'Derrotas': 0, 'Empates': 0, 'Pontos': 0}

        if away_team not in estatisticas_2023:
            estatisticas_2023[away_team] = {'Vitórias': 0, 'Derrotas': 0, 'Empates': 0, 'Pontos': 0}

        if resultado == 'H':
            estatisticas_2023[home_team]['Vitórias'] += 1
            estatisticas_2023[home_team]['Pontos'] += 3
            estatisticas_2023[away_team]['Derrotas'] += 1
        elif resultado == 'A':
            estatisticas_2023[home_team]['Derrotas'] += 1
            estatisticas_2023[away_team]['Vitórias'] += 1
            estatisticas_2023[away_team]['Pontos'] += 3
        else:
            estatisticas_2023[home_team]['Empates'] += 1
            estatisticas_2023[home_team]['Pontos'] += 1
            estatisticas_2023[away_team]['Empates'] += 1
            estatisticas_2023[away_team]['Pontos'] += 1

    df_estatisticas_2023 = pd.DataFrame.from_dict(estatisticas_2023, orient='index')

    df_estatisticas_2023 = df_estatisticas_2023.sort_values(by='Pontos', ascending=False)

    df_estatisticas_2023['Ranking'] = range(1, len(df_estatisticas_2023) + 1)

    df_estatisticas_2023 = df_estatisticas_2023.reset_index().rename(columns={'index': 'Time'})

    df_estatisticas_2023 = df_estatisticas_2023[['Ranking', 'Time', 'Vitórias', 'Empates', 'Derrotas', 'Pontos']]

    print(tabulate(df_estatisticas_2023, headers='keys', tablefmt='pipe', showindex=False, stralign='center', numalign='center'))